
spring:
  application:
    name: movie-media-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${MOVIE_TICKETS_AUTH_ISSUER_URI}
          jwk-set-uri: ${MOVIE_TICKETS_AUTH_JWK_SET_URI}
  jpa:
    open-in-view: false
  datasource:
    url: ${MOVIE_TICKETS_POSTGRESQL_URL}
    username: ${MOVIE_TICKETS_POSTGRESQL_USERNAME}
    password: ${MOVIE_TICKETS_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 100MB
      file-size-threshold: 0B
      location: ${java.io.tmpdir}
      max-request-size: 100MB

server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 4
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        security: DEBUG