spring:
  application:
    name: movie-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${MOVIE_TICKETS_AUTH_ISSUER_URI}
          jwk-set-uri: ${MOVIE_TICKETS_AUTH_JWK_SET_URI}
  jpa:
    open-in-view: false

  datasource:
    url: ${MOVIE_TICKETS_POSTGRESQL_URL}
    username: ${MOVIE_TICKETS_POSTGRESQL_USERNAME}
    password: ${MOVIE_TICKETS_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: false

server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 4
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
