spring:
  application:
    name: shopping-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${MOVIE_TICKETS_AUTH_ISSUER_URI}
          jwk-set-uri: ${MOVIE_TICKETS_AUTH_JWK_SET_URI}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    converters:
      preferred-json-mapper: jackson
  datasource:
    url: ${MOVIE_TICKETS_POSTGRESQL_URL}
    username: ${MOVIE_TICKETS_POSTGRESQL_USERNAME}
    password: ${MOVIE_TICKETS_POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: false

server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 4
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${MOVIE_TICKETS_EUREKA_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true

springdoc:
  api-docs:
    path: "/v3/api-docs/purchase-service"

com:
  larasierra:
    stripe_sk: ${MOVIE_TICKETS_STRIPE_SK}
    stripe_whsec: ${MOVIE_TICKETS_STRIPE_WHSEC}
